// ─────────────────────────────────────────────────────────────────────────
// AIPROSOL · Stripe client (server-side only)
// Wraps the Stripe SDK with our config. Never import this from a client
// component — that would expose the secret key.
// ─────────────────────────────────────────────────────────────────────────

import Stripe from 'stripe';

const apiKey = process.env.STRIPE_SECRET_KEY;

export const stripe = apiKey
  ? new Stripe(apiKey, {
      apiVersion: '2024-12-18.acacia' as Stripe.LatestApiVersion,
      typescript: true,
      appInfo: { name: 'Aiprosol', version: '3.0.0' },
    })
  : null;

export const isStripeConfigured = (): boolean => Boolean(apiKey);

/**
 * Resolve the Stripe Price ID for a given local product/plan slug.
 * Reads from src/content/stripe-prices.json (generated by `npm run seed:stripe`).
 * Falls back to looking at the relevant content file's `stripePriceId` field.
 */
export async function resolvePriceId(slug: string): Promise<string | null> {
  try {
    // Lazy-load so this works even before the seed script has run.
    const { default: priceMap } = await import('@/content/stripe-prices.json').catch(() => ({ default: {} as Record<string, string> }));
    const direct = (priceMap as Record<string, string>)[slug];
    if (direct) return direct;
  } catch {}

  // Secondary: look in products / plans
  try {
    const { getProductBySlug, getPricingPlan } = await import('@/lib/content');
    const product = getProductBySlug(slug);
    if (product?.stripePriceId) return product.stripePriceId;
    if (slug === 'starter' || slug === 'growth' || slug === 'enterprise') {
      const plan = getPricingPlan(slug);
      if (plan?.stripePriceId) return plan.stripePriceId;
    }
  } catch {}

  return null;
}
