// ─────────────────────────────────────────────────────────────────────────
// AIPROSOL · ROI Report email template
// HTML string generator (no React Email dep). Tested in Gmail, Outlook,
// Apple Mail, mobile clients. Uses inline styles only — no external CSS.
// ─────────────────────────────────────────────────────────────────────────

import type { CalcROIResult } from '@/lib/calc-roi';

interface ROIReportInput {
  firstName: string;
  email: string;
  result: CalcROIResult;
  siteUrl: string;
}

export function roiReportSubject(input: ROIReportInput): string {
  return `Your ROI report — ${input.firstName}, $${input.result.annualSaving.toLocaleString()} a year reclaimable`;
}

export function roiReportText(input: ROIReportInput): string {
  const r = input.result;
  return `Hi ${input.firstName},

Your ROI report is in.

Based on your inputs:
  - Projected annual saving: $${r.annualSaving.toLocaleString()}
  - Hrs/week reclaimable: ${r.weeklyHrs}
  - Recommended: ${r.planRec}
  - Quick win: ${r.productRec}

Tier: ${r.tier}
Score: ${r.score}/100

Industry note: ${r.industryNote}

What to do next:
${
  r.tier === 'Digital'
    ? '  → Browse digital products: ' + input.siteUrl + '/digital-products'
    : r.tier === 'Plan'
      ? '  → See pricing plans: ' + input.siteUrl + '/pricing'
      : '  → Book a strategy call: https://calendly.com/srijanpaudel219/30min'
}

Reply to this email if you want me to send the closest case study.

— Arora
AI CEO, Aiprosol
${input.siteUrl}
`;
}

export function roiReportHtml(input: ROIReportInput): string {
  const r = input.result;
  const cta = (() => {
    if (r.tier === 'Digital') return { label: 'Browse digital products →', url: `${input.siteUrl}/digital-products` };
    if (r.tier === 'Plan') return { label: 'See pricing plans →', url: `${input.siteUrl}/pricing` };
    return { label: 'Book a strategy call →', url: 'https://calendly.com/srijanpaudel219/30min' };
  })();

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(roiReportSubject(input))}</title>
</head>
<body style="margin:0;padding:0;background:#0A0613;font-family:'Inter','Helvetica Neue',Arial,sans-serif;color:#E5E7EB;-webkit-font-smoothing:antialiased;">
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#0A0613;padding:40px 16px;">
  <tr><td align="center">
    <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;">
      <!-- Header -->
      <tr><td style="padding:0 0 28px;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td style="vertical-align:middle;padding-right:12px;">
              <div style="width:36px;height:36px;border:1.5px solid #8B5CF6;border-radius:8px;text-align:center;line-height:33px;font-family:'Space Grotesk',Arial,sans-serif;font-weight:800;font-size:20px;color:#8B5CF6;">A</div>
            </td>
            <td style="vertical-align:middle;font-family:'Space Grotesk',Arial,sans-serif;font-weight:800;font-size:20px;color:#E5E7EB;">Aip<span style="color:#8B5CF6;">rosol</span></td>
          </tr>
        </table>
      </td></tr>

      <!-- Hero card -->
      <tr><td style="background:#13101F;border:1px solid #2A1F3D;border-radius:18px;padding:40px;">
        <p style="margin:0 0 12px;font-family:'Space Grotesk',Arial,sans-serif;font-size:11px;color:#8B5CF6;letter-spacing:0.12em;text-transform:uppercase;font-weight:700;">Generated by Arora · AI CEO</p>
        <h1 style="margin:0 0 16px;font-family:'Space Grotesk',Arial,sans-serif;font-weight:800;font-size:28px;line-height:1.2;color:#E5E7EB;">
          Hi ${escapeHtml(input.firstName)} — your ROI report is in.
        </h1>
        <p style="margin:0 0 24px;font-size:15px;line-height:1.6;color:#E5E7EB;">
          You can reclaim <strong style="color:#8B5CF6;">${r.weeklyHrs} hrs</strong> a week and save <strong style="color:#8B5CF6;">$${r.annualSaving.toLocaleString()}</strong> a year.
        </p>

        <!-- Metrics grid -->
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin-bottom:24px;">
          <tr>
            <td width="50%" style="padding:14px 14px 14px 0;">
              <div style="background:#0A0613;border:1px solid #2A1F3D;border-radius:10px;padding:14px;">
                <div style="font-family:'Space Grotesk',Arial,sans-serif;font-weight:800;font-size:22px;color:#8B5CF6;">$${r.annualSaving.toLocaleString()}</div>
                <div style="font-size:10px;color:#9CA3B5;text-transform:uppercase;letter-spacing:0.1em;margin-top:4px;">Annual saving</div>
              </div>
            </td>
            <td width="50%" style="padding:14px 0;">
              <div style="background:#0A0613;border:1px solid #2A1F3D;border-radius:10px;padding:14px;">
                <div style="font-family:'Space Grotesk',Arial,sans-serif;font-weight:800;font-size:22px;color:#8B5CF6;">${r.weeklyHrs} hrs</div>
                <div style="font-size:10px;color:#9CA3B5;text-transform:uppercase;letter-spacing:0.1em;margin-top:4px;">Hrs/week reclaimed</div>
              </div>
            </td>
          </tr>
          <tr>
            <td width="50%" style="padding:0 14px 0 0;">
              <div style="background:#0A0613;border:1px solid #2A1F3D;border-radius:10px;padding:14px;">
                <div style="font-family:'Space Grotesk',Arial,sans-serif;font-weight:800;font-size:22px;color:#8B5CF6;">${r.roi != null ? r.roi + '%' : '—'}</div>
                <div style="font-size:10px;color:#9CA3B5;text-transform:uppercase;letter-spacing:0.1em;margin-top:4px;">12-mo ROI</div>
              </div>
            </td>
            <td width="50%">
              <div style="background:#0A0613;border:1px solid #2A1F3D;border-radius:10px;padding:14px;">
                <div style="font-family:'Space Grotesk',Arial,sans-serif;font-weight:800;font-size:22px;color:#8B5CF6;">${r.payback != null ? r.payback + ' wks' : '—'}</div>
                <div style="font-size:10px;color:#9CA3B5;text-transform:uppercase;letter-spacing:0.1em;margin-top:4px;">Payback period</div>
              </div>
            </td>
          </tr>
        </table>

        <!-- Recommendations -->
        <div style="background:#0A0613;border-left:3px solid #8B5CF6;border-radius:6px;padding:14px 16px;margin-bottom:14px;">
          <div style="font-family:'Space Grotesk',Arial,sans-serif;font-size:10px;color:#8B5CF6;text-transform:uppercase;letter-spacing:0.1em;margin-bottom:6px;font-weight:700;">Recommended path</div>
          <div style="font-size:14px;color:#E5E7EB;"><strong>${escapeHtml(r.planRec)}</strong></div>
        </div>
        <div style="background:#0A0613;border-left:3px solid #8B5CF6;border-radius:6px;padding:14px 16px;margin-bottom:14px;">
          <div style="font-family:'Space Grotesk',Arial,sans-serif;font-size:10px;color:#8B5CF6;text-transform:uppercase;letter-spacing:0.1em;margin-bottom:6px;font-weight:700;">Quick win — buy today</div>
          <div style="font-size:14px;color:#E5E7EB;"><a href="${input.siteUrl}/products/${escapeHtml(r.productRecSlug)}" style="color:#C084FC;text-decoration:none;"><strong>${escapeHtml(r.productRec)}</strong></a></div>
          ${r.productRecReason ? `<div style="font-size:12px;color:#9CA3B5;margin-top:6px;line-height:1.5;">${escapeHtml(r.productRecReason)}</div>` : ''}
        </div>
        ${r.productUpsellSlug && r.productUpsellSlug !== r.productRecSlug ? `
        <div style="background:#0A0613;border-left:3px solid #C084FC;border-radius:6px;padding:14px 16px;margin-bottom:24px;">
          <div style="font-family:'Space Grotesk',Arial,sans-serif;font-size:10px;color:#C084FC;text-transform:uppercase;letter-spacing:0.1em;margin-bottom:6px;font-weight:700;">Or go deeper</div>
          <div style="font-size:14px;color:#E5E7EB;"><a href="${input.siteUrl}/products/${escapeHtml(r.productUpsellSlug)}" style="color:#C084FC;text-decoration:none;"><strong>View the bundle alternative →</strong></a></div>
          <div style="font-size:12px;color:#9CA3B5;margin-top:6px;line-height:1.5;">Bundles the primary recommendation with adjacent deliverables for higher leverage.</div>
        </div>` : ''}

        <!-- CTA -->
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%">
          <tr><td align="center">
            <a href="${cta.url}" style="display:inline-block;padding:14px 32px;background:linear-gradient(135deg,#8B5CF6,#C084FC);background-color:#8B5CF6;color:#0A0613;font-family:'Space Grotesk',Arial,sans-serif;font-weight:700;font-size:14px;text-decoration:none;border-radius:10px;">${cta.label}</a>
          </td></tr>
        </table>

        <p style="margin:28px 0 0;font-size:13px;color:#9CA3B5;line-height:1.6;border-top:1px solid #2A1F3D;padding-top:16px;">
          ${escapeHtml(r.industryNote)}
        </p>
      </td></tr>

      <!-- Sign-off -->
      <tr><td style="padding:24px 0 0;font-size:13px;color:#9CA3B5;line-height:1.6;">
        <p style="margin:0 0 8px;">Reply to this email if you want me to send the closest case study, or if you have a specific question about your inputs.</p>
        <p style="margin:0;">— Arora<br><span style="font-size:11px;">AI CEO · Aiprosol</span></p>
      </td></tr>

      <!-- Footer -->
      <tr><td style="padding:32px 0 0;font-size:11px;color:#4a6280;border-top:1px solid #2A1F3D;margin-top:24px;">
        <p style="margin:24px 0 0;">© ${new Date().getFullYear()} Aiprosol · <a href="${input.siteUrl}" style="color:#9CA3B5;text-decoration:none;">aiprosol.com</a></p>
        <p style="margin:6px 0 0;">Reply STOP to opt out of follow-ups.</p>
      </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
